siganushka_media:
    # storage: Siganushka\MediaBundle\Storage\AliyunOssStorage
    media_class: App\Entity\Media
    rules:
        test_img:
            constraint: image
            constraint_options: { mimeTypes: ['image/*'] }
            resize: true
            optimize: true
        test_video:
            constraint: video
            constraint_options: { minWidth: 1280, minHeight: 720 }
        test_pdf:
            constraint_options: { extensions: ['pdf'] }
