siganushka_media:
    # storage: Siganushka\MediaBundle\Storage\AliyunOssStorage
    media_class: App\Entity\Media
    rules:
        test_img:
            constraint: image
            constraint_options: { mimeTypes: ['image/*'] }
            resize: 1000
            optimize: 70
        test_pdf:
            constraint: file
            constraint_options: { mimeTypes: ['application/pdf', 'application/x-pdf'] }
