siganushka_region:
    resource: "@SiganushkaRegionBundle/config/routes.php"
    prefix: /api

siganushka_media:
    resource: "@SiganushkaMediaBundle/config/routes.php"
    prefix: /api

siganushka_product:
    resource: "@SiganushkaProductBundle/config/routes.php"
    prefix: /api

siganushka_order:
    resource: "@SiganushkaOrderBundle/config/routes.php"
    prefix: /api

siganushka_user:
    resource: "@SiganushkaUserBundle/config/routes.php"
    prefix: /api

when@dev:
    siganushka_generic:
        resource: "@SiganushkaGenericBundle/config/routes.php"
