App\Entity\RandomDiscount:
    attributes:
        id:
            groups: ['order:item', 'order:collection']
        order:
            groups: []
        amount:
            groups: ['order:item', 'order:collection']
        type:
            groups: ['order:item', 'order:collection']
        label:
            groups: ['order:item', 'order:collection']
        createdAt:
            groups: ['order:item', 'order:collection']