App\Entity\Region:
    attributes:
        code:
            groups: ['region:item', 'region:collection']
        name:
            groups: ['region:item', 'region:collection']
        fullname:
            groups: ['region:item', 'region:collection']
        level:
            groups: ['region:item', 'region:collection']
        parent:
            groups: []
        children:
            groups: []
        ancestors:
            groups: []
        siblings:
            groups: []
        descendants:
            groups: []
        depth:
            groups: []
        root:
            groups: ['region:item', 'region:collection']
        leaf:
            groups: ['region:item', 'region:collection']
