App\Entity\TestNestable:
    attributes:
        id:
            groups: []
        parent:
            groups: []
        children:
            groups: []
        ancestors:
            groups: []
        siblings:
            groups: []
        descendants:
            groups: []
        depth:
            groups: []
        root:
            groups: []
        leaf:
            groups: []
