App\Entity\ProductOptionValue:
    attributes:
        id:
            groups: ['product_option:item', 'product:item', 'product:collection']
        option:
            groups: []
        code:
            groups: ['product_option:item', 'product:item', 'product:collection']
        text:
            groups: ['product_option:item', 'product:item', 'product:collection']
        img:
            groups: ['product_option:item', 'product:item', 'product:collection']
        variants:
            groups: []
        variantsCount:
            groups: ['product_option:item', 'product:item', 'product:collection']
        createdAt:
            groups: ['product_option:item', 'product:item', 'product:collection']
        updatedAt:
            groups: ['product_option:item', 'product:item', 'product:collection']
