App\Entity\ProductVariant:
    attributes:
        id:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        product:
            groups: []
        code:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        name:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        price:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        stock:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        img:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        optionValues:
            ignore: true
        subjectTitle:
            ignore: true
        subjectPrice:
            ignore: true
        subjectExtra:
            ignore: true
        subjectImg:
            ignore: true
        availableStock:
            ignore: true
        outOfStock:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        version:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        enabled:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        createdAt:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
        updatedAt:
            groups: ['product_variant:item', 'product_variant:collection', 'product:item', 'product:collection']
