# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

siganushka_generic:
    resource: "@SiganushkaGenericBundle/config/routes.php"

siganushka_region:
    resource: "@SiganushkaRegionBundle/config/routes.php"
    prefix: /api
    stateless: true

siganushka_media:
    resource: "@SiganushkaMediaBundle/config/routes.php"
    prefix: /api
    stateless: true

siganushka_product:
    resource: "@SiganushkaProductBundle/config/routes.php"
    prefix: /api
    stateless: true

siganushka_order:
    resource: "@SiganushkaOrderBundle/config/routes.php"
    prefix: /api
    stateless: true

siganushka_user:
    resource: "@SiganushkaUserBundle/config/routes.php"
    prefix: /api
    stateless: true
