# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    siganushka_generic.form.money_type_extension:
        class: Siganushka\GenericBundle\Form\Extension\MoneyTypeExtension
        arguments: { $locale: '%env(APP_LOCALE)%', $currency: '%env(APP_CURRENCY)%' }

    # Siganushka\MediaBundle\Storage\LocalStorage:
    #     $publicDir: '%kernel.project_dir%/public'
    #     $options: { prefix_dir: uploads }

    Siganushka\MediaBundle\Storage\AliyunOssStorage:
        $accessKeyId: '%env(string:ALIYUN_ACCESS_KEY_ID)%'
        $accessKeySecret: '%env(string:ALIYUN_ACCESS_KEY_SECRET)%'
        $endpoint: '%env(string:ALIYUN_OSS_ENDPOINT)%'
        $bucket: '%env(string:ALIYUN_OSS_BUCKET)%'
        $options: { prefix_dir: test, cname: '%env(bool:ALIYUN_OSS_CNAME)%' }

    Siganushka\MediaBundle\Storage\HuaweiObsStorage:
        $accessKeyId: '%env(string:HUAWEI_ACCESS_KEY_ID)%'
        $accessKeySecret: '%env(string:HUAWEI_ACCESS_KEY_SECRET)%'
        $endpoint: '%env(string:HUAWEI_OBS_ENDPOINT)%'
        $bucket: '%env(string:HUAWEI_OBS_BUCKET)%'
        $options: { prefix_dir: test, is_cname: '%env(bool:HUAWEI_OBS_CNAME)%' }
